version: "3.9"

services:
  dbservice:
    image: mysql:8.0
    container_name: chattingo-db
    environment:
      MYSQL_ROOT_PASSWORD: chattingo123
      MYSQL_DATABASE: chattingo_db
    ports:
      - "3308:3306"
    networks:
      - appnet
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  appservice:
    build:
      context: ./backend
    container_name: chattingo-app
    depends_on:
      dbservice:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbservice:3306/chattingo_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: chattingo123
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      cors.allowed.origins: "*"
    ports:
      - "8081:8080"
    networks:
      - appnet

  web:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://chattingo.shaheen.homes
    container_name: chattingo-web
    depends_on:
      - appservice
    ports:
      - "80:80"
    networks:
      - appnet

volumes:
  mysql-data:

networks:
  appnet:

